spring:
  datasource:
    url: jdbc:mysql://localhost:3306/historyIntroduction
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
#Port
server:
  port: 8080

mail:
  username: nguyenvanquang16092001@gmail.com
  password: 29072001