spring:
  datasource:
    url: jdbc:mysql://localhost:3306/historyintroduction
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#Port
server:
  port: 8080

mail:
  username: nguyenvanquang16092001@gmail.com
  password: quangnvuet1609