spring:
  datasource:
    url: jdbc:mysql://localhost:3306/historyintroduction
    username: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

#Port
server:
  port: 8080

mail:
  username: nguyenvanquang16092001@gmail.com
  password: quangnvuet1609